Los avances de la validacion del boton
jesusantonio98/login pull request #7
Opened 2020-09-09 18:52 UTC by crisstianca

Aqui dejo mis avances del dia

2020-09-09 19:14 UTC, joshet8 requested changes

2020-09-09 19:14 UTC, joshet8 commented on index.html
> +
Aqui hiciste un cambio innecesario pues veo que es un espacio ahora hay 2 espacios y pues alcontrario no deberia llevar espacios

2020-09-09 19:14 UTC, joshet8 commented on index.html
> +							<input type="text" id="usuario" value="otro valor" class="form-control mb-2 mr-sm-2" id="user-group" name ="username" autocomplete="off" placeholder="usuario" onInput="validarInput()">
que es eso de onpput y esa funcion no esta definida

2020-09-09 19:14 UTC, joshet8 commented on static/css/index.css
> +	content: "\f007";
estas subiendo como si tu huveras ehco esta modificacion para eso se verifica que cambio voy a subir para no subir cambios que no son necesarios

2020-09-11 05:16 UTC, crisstianca commented on index.html
> +							<input type="text" id="usuario" value="otro valor" class="form-control mb-2 mr-sm-2" id="user-group" name ="username" autocomplete="off" placeholder="usuario" onInput="validarInput()">
El autocomplete es para que la caja usuario deje de recordar los que se hayan escrito antes. esa función del onIput ya se lo quitare.

2020-09-11 23:14 UTC, joshet8 approved these changes

2020-09-21 16:49 UTC, merged